config/routes.rb
Rails.application.routes.draw do
  resources :domain_crawlers
  resources :search_queries
  resources :group_names
  resources :search_results
  resources :regex_templates
  get 'password_resets/new'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'

  get 'logout', to: 'sessions#destroy', as: 'logout'

  get "/set_header" => 'domain_crawlers#set_header', as: 'set_header'

  get "/display_group" => 'domain_crawlers#display_group', as: 'display_group'

  get "/delete_result" => 'domain_crawlers#delete_result', as: 'delete_result'

  post 'search', to: 'domain_crawlers#search', as: 'search'

  get 'group_action', to: 'domain_crawlers#group_action', as: 'group_action'
  get 'expand_contract_action', to: 'domain_crawlers#expand_contract_action', as: 'expand_contract_action'
  get 'apple-touch-icon-120x120-precomposed.png', to: redirect('/assets/favicon/apple-touch-icon-120x120-precomposed.png')
  get 'apple-touch-icon-120x120.png', to: redirect('/assets/favicon/apple-touch-icon-120x120.png')
  get 'apple-touch-icon.png', to: redirect('/assets/favicon/apple-touch-icon.png')
  get 'apple-touch-icon-precomposed.png', to: redirect('/assets/favicon/apple-touch-icon-precomposed.png')
  get 'apple-touch-icon-152x152.png', to: redirect('/assets/favicon/apple-touch-icon-152x152.png')
  get 'apple-touch-icon-152x152-precomposed.png', to: redirect('/assets/favicon/apple-touch-icon-152x152-precomposed.png')


  get 'domain_action', to: 'domain_crawlers#domain_action', as: 'domain_action'
  get 'more_results', to: 'domain_crawlers#more_results', as: 'more_results'
  get 'process_more_results', to: 'domain_crawlers#process_more_results', as: 'process_more_results'
  get 'previous_search', to: 'domain_crawlers#previous_search', as: 'previous_search'
  get 'tidy_up', to: 'domain_crawlers#tidy_up', as: 'tidy_up'
  post 'add_result', to:'domain_crawlers#add_result', as: 'add_result'
  post 'remove_group_result', to:'domain_crawlers#remove_group_result', as: 'remove_group_result'


  resources :users
  resources :sessions
  resources :password_resets


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'users#index'
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    user.send_password_reset if user
    redirect_to root_url, :notice => "Email sent with password reset instructions."
  end

  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end

  def update
    @user = User.find_by_password_reset_token!(params[:id])
    if @user.password_reset_sent_at < 2.hours.ago
      redirect_to new_password_reset_path, :alert => "Password reset has expired."
    elsif @user.update_attributes(params.permit![:user])
      redirect_to root_url, :notice => "Password has been reset!"
    else
      render :edit
    end
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<h1>Reset Password</h1>

<%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>
    <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% for message in @user.errors.full_messages %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="actions"><%= f.submit "Update Password" %></div>
<% end %>

<script>HideForms();</script>

app/views/password_resets/new.html.erb
<h1>Reset Password</h1>
<%= form_tag password_resets_path, :method => :post do %>
    <div class="field">
      <%= label_tag :email %>
      <%= text_field_tag :email, params[:email] %>
    </div>
    <div class="actions"><%= submit_tag "Reset Password" %></div>
<% end %>

<script>HideForms();</script>