config/routes.rb
Rails.application.routes.draw do
  resources :domain_crawlers
  resources :search_queries
  resources :group_names
  resources :search_results
  resources :regex_templates
  get 'password_resets/new'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'

  get 'logout', to: 'sessions#destroy', as: 'logout'

  get "/set_header" => 'domain_crawlers#set_header', as: 'set_header'

  get "/display_group" => 'domain_crawlers#display_group', as: 'display_group'

  get "/delete_result" => 'domain_crawlers#delete_result', as: 'delete_result'

  post 'search', to: 'domain_crawlers#search', as: 'search'

  get 'group_action', to: 'domain_crawlers#group_action', as: 'group_action'
  get 'expand_contract_action', to: 'domain_crawlers#expand_contract_action', as: 'expand_contract_action'
  get 'apple-touch-icon-120x120-precomposed.png', to: redirect('/assets/favicon/apple-touch-icon-120x120-precomposed.png')
  get 'apple-touch-icon-120x120.png', to: redirect('/assets/favicon/apple-touch-icon-120x120.png')
  get 'apple-touch-icon.png', to: redirect('/assets/favicon/apple-touch-icon.png')
  get 'apple-touch-icon-precomposed.png', to: redirect('/assets/favicon/apple-touch-icon-precomposed.png')
  get 'apple-touch-icon-152x152.png', to: redirect('/assets/favicon/apple-touch-icon-152x152.png')
  get 'apple-touch-icon-152x152-precomposed.png', to: redirect('/assets/favicon/apple-touch-icon-152x152-precomposed.png')


  get 'domain_action', to: 'domain_crawlers#domain_action', as: 'domain_action'
  get 'more_results', to: 'domain_crawlers#more_results', as: 'more_results'
  get 'process_more_results', to: 'domain_crawlers#process_more_results', as: 'process_more_results'
  get 'previous_search', to: 'domain_crawlers#previous_search', as: 'previous_search'
  get 'tidy_up', to: 'domain_crawlers#tidy_up', as: 'tidy_up'
  post 'add_result', to:'domain_crawlers#add_result', as: 'add_result'
  post 'remove_group_result', to:'domain_crawlers#remove_group_result', as: 'remove_group_result'


  resources :users
  resources :sessions
  resources :password_resets


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'users#index'
end

app/models/search_result.rb
require 'nokogiri'
require 'open-uri'
require 'digest/md5'

class SearchResult < ApplicationRecord
  # @param [String] url
  # @param [String] base_url
  # @param [number] current_level
    # @return [Object]
  has_many :group_elements, :dependent => :destroy

  def self.ProcessHash(url, current_level)

      max_crawl_number = 5
      crawl_number =0
      last_slash = url.rindex("/")
      base_url = url[0,last_slash+1]
      if last_slash < url.length-1
        file_name = url[last_slash+1,url.size]
      else
        file_name = ''
      end



      logger.debug "process_hash url: #{url}, base_url: #{base_url}, file_name: #{file_name}, level: #{current_level}"
      next_level = current_level+1
      new_pages = Set.new
      begin
        doc = Nokogiri::HTML(open(url))
        body = doc.css("body")
        #blogger.debug "Body is #{body}"

        hash_value = Digest::MD5.hexdigest(body)
        if(ResultPage.find_by_URL(url)!=nil)
          result_page = ResultPage.new
          result_page.user_id = current_user
          result_page.URL = url
          result_page.content = body
          result_page.hash_value = hash_value
          result_page.save
          logger.debug "Saved url #{url}"
        end
        links = doc.css("a")
        links.each do |item|

          logger.debug "Href1: #{item['href'].inspect}, #{item['href'].class}"

          href_str = item["href"]
          if href_str =~ /^#{base_url}/
            logger.debug "we have a match for #{href_str}"
            href_str.sub! base_url, ''
            logger.debug "Updated: #{href_str}"
          elsif href_str.nil? or href_str =~ /\#/ or href_str =~ /^javascript/
            logger.debug "Nil case: #{href_str}"
          elsif href_str !~ /^http:/ and href_str !~ /^https:/ and crawl_number < max_crawl_number

            @@current_pages[base_url+href_str] ||= next_level
            new_pages.add(base_url+href_str)
            crawl_number=crawl_number+1

          end
        end
      rescue Exception => e
          logger.debug "Couldn't read \"#{ url }\": #{ e }"
      end

      new_pages.each do |url|
        logger.debug "let's sleep"
        sleep(10)
        self.ProcessHash(url, next_level)
      end if next_level < @@max_level

    end

  def self.search(search)
    url = "http://www.dhspriory.org/thomas/english/ContraGentiles.htm"

    @@max_level = 2
    current_level = 0
    @@current_pages = Hash.new()
    @@current_pages[url] = current_level
    self.ProcessHash(url, current_level)
    count = 1
    @@current_pages.each do |page, level|
      logger.debug "#{count}: Page = #{page}, Level = #{level}"
      count = count+1
    end





    logger.debug "New article: lalalalallalalallalallalallalallalallal"
    if search
      wildcard_search = "%#{search}%"
      all

    else
      all
    end

  end
end

app/controllers/search_results_controller.rb
class SearchResultsController < ApplicationController
  def index
    @search_results = SearchResult.search(params[:search])
  end
end

app/helpers/search_results_helper.rb
module SearchResultsHelper


end

app/views/search_results/_display_results.html.erb
<div id="search-results">

  <%= form_tag more_results_path, :id => 'more_results_form', method: 'get', remote: true do %>
      <%= text_field_tag :results_current_index, params[:current_index] %>
      <%= text_field_tag :results_range, params[:range] %>
      <%= text_field_tag :results_query_id, params[:query_id], :value => args[:query_id] %>
      <div class="next-prev"><%= submit_tag "More Results", id: "next-prev-button" %></div>
  <% end %>
  <%= form_tag process_more_results_path, :id => 'process_more_results_form', method: 'get', remote: true do %>
      <%= text_field_tag :more_results_query_id, params[:query_id], :value => args[:query_id] %>
      <%= text_field_tag :more_results_first_result_id, params[:first_result_id], :value => args[:first_result_id] %>
      <%= text_field_tag :more_results_last_result_id, params[:last_result_id], :value => args[:last_result_id] %>
      <div class="next-prev"><%= submit_tag "Process More Results", id: "process-more-button" %></div>
  <% end %>

  <%= form_tag tidy_up_path, :id => 'tidy_up_form', method: 'get', remote: true do %>
      <%= text_field_tag :tidy_user_id, params[:tidy_user_id], :value => args[:user_id] %>
      <div class="next-prev"><%= submit_tag "Tidy Up Now", id: "tidy-up-button" %></div>
  <% end %>

  <% if @search_results.length >0 %>

       <% group_ids = [] %>



      <% crawler_page_id = -1000 %>
      <% group_str = "" %>


      <%= form_tag add_result_path, :id => 'add_result_form', method: 'post', remote: true do %>
          <% @search_results.first(MAX_DISPLAY).each do |search_result| %>
              <% if search_result.crawler_page_id != -1 %>
                  <% if @search_groups1 %>

                 <% new_groups = GroupName.find_by_sql("SELECT * FROM group_names gn WHERE gn.user_id = #{current_user.id} AND (SELECT COUNT(*) FROM group_elements ge INNER JOIN search_results sr ON sr.id = ge.search_result_id WHERE ge.group_name_id = gn.id AND sr.begin_display_paragraph_id = #{search_result.begin_display_paragraph_id}) >0 ORDER BY gn.id ASC")%>
                 <% new_group_ids = new_groups.map{|gn| gn.id} %>
                      <% logger.info "**************** new_groups = #{new_groups.inspect}"%>
                  <% if new_group_ids != group_ids %>
                      <% group_ids = new_group_ids %>

                          <% group_list = new_groups.map{|gn| "<#{gn.name}>"}.join(' ,')%>
                          <% group_str = ", Groups: " + group_list %>


                          <% else %>
                          <% group_str = "" %>
                          <% end %>

                      <% end %>
                  <% logger.info "***** group_str = #{group_str}, search_groups1 = #{@search_groups1}"%>
                  <% if search_result.crawler_page_id != crawler_page_id or group_str.length > 0 %>
                      <% crawler_page_id = search_result.crawler_page_id %>
                      <% crawler_page = CrawlerPage.find_by_id(crawler_page_id) %>
                      <% download_date = crawler_page.download_date %>
                      <div class="page-results">
                        <%= link_to crawler_page.URL+download_date.strftime(" (Access date: %b %e, %Y) ") + group_str, crawler_page.URL, target: '_blank' %>
                      </div>
                  <% end %>
                  <div class="search-result-outer" name="search-result-<%= search_result.id %>">
                    <div class="search-result-text">
                      <%= raw(search_result.highlighted_result) %>
                    </div>
          <span class="search-check-box ">
            <input type="checkbox" id="checkbox-search-result-<%= search_result.id %>" name="search_result_list[]" class="check" value=<%= search_result.id %>>
          </span>
                    <span class="delete-link"> <%= link_to 'delete', delete_result_path(:id => search_result.id), :remote => true %> </span>
                  </div>
              <% end %>
          <% end %>
          <%= text_field_tag :add_elements_group_id, params[:add_elements_group_id] %>
          <div class="actions search-action-button"><%= submit_tag "Add Selected", id: "search-action-button" %></div>
      <% end %>
      <br>
  <% else %>
      <div class="no-results">No results found</div>
  <% end %>
</div>