config/routes.rb
Rails.application.routes.draw do
  resources :domain_crawlers
  resources :search_queries
  resources :group_names
  resources :search_results
  resources :regex_templates
  get 'password_resets/new'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'

  get 'logout', to: 'sessions#destroy', as: 'logout'

  get "/set_header" => 'domain_crawlers#set_header', as: 'set_header'

  get "/display_group" => 'domain_crawlers#display_group', as: 'display_group'

  get "/delete_result" => 'domain_crawlers#delete_result', as: 'delete_result'

  post 'search', to: 'domain_crawlers#search', as: 'search'

  get 'group_action', to: 'domain_crawlers#group_action', as: 'group_action'
  get 'expand_contract_action', to: 'domain_crawlers#expand_contract_action', as: 'expand_contract_action'
  get 'apple-touch-icon-120x120-precomposed.png', to: redirect('/assets/favicon/apple-touch-icon-120x120-precomposed.png')
  get 'apple-touch-icon-120x120.png', to: redirect('/assets/favicon/apple-touch-icon-120x120.png')
  get 'apple-touch-icon.png', to: redirect('/assets/favicon/apple-touch-icon.png')
  get 'apple-touch-icon-precomposed.png', to: redirect('/assets/favicon/apple-touch-icon-precomposed.png')
  get 'apple-touch-icon-152x152.png', to: redirect('/assets/favicon/apple-touch-icon-152x152.png')
  get 'apple-touch-icon-152x152-precomposed.png', to: redirect('/assets/favicon/apple-touch-icon-152x152-precomposed.png')


  get 'domain_action', to: 'domain_crawlers#domain_action', as: 'domain_action'
  get 'more_results', to: 'domain_crawlers#more_results', as: 'more_results'
  get 'process_more_results', to: 'domain_crawlers#process_more_results', as: 'process_more_results'
  get 'previous_search', to: 'domain_crawlers#previous_search', as: 'previous_search'
  get 'tidy_up', to: 'domain_crawlers#tidy_up', as: 'tidy_up'
  post 'add_result', to:'domain_crawlers#add_result', as: 'add_result'
  post 'remove_group_result', to:'domain_crawlers#remove_group_result', as: 'remove_group_result'


  resources :users
  resources :sessions
  resources :password_resets


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'users#index'
end

app/controllers/domain_crawlers_controller.rb
class DomainCrawlersController < ApplicationController
  def index
    @result_str = ""
    logger.info "DomainCrawlersController index called with method #{params[:method]}"
    @users = User.all


    case params[:method]
      when "set_header"
        logger.info "DomainCrawlersController case set_header"

      when "index"
        logger.info "DomainCrawlersController case index"
      else
        logger.info "DomainCrawlersController case else"
    end

    # @crawl_results = DomainCrawler.crawl(params[:domain], current_user.id)
    # flash.now.alert = @crawl_results
    # redirect_to action: "show", id: current_domain_crawler
  end

  def new
    logger.info "DomainCrawlersController new called"
    @users = User.all
    @domain_crawler = DomainCrawler.new
    @result_str = ""


    #   logger.info "DomainCrawlersController new called @domain_crawler id set to #{@domain_crawler.id}"
  end

  def crawler_debug
    crawler_page = CrawlerPage.where(id: 3)
    logger.info "crawler_page: #{crawler_page.inspect}"
    descendents = crawler_page.root.descendants.arrange
    descendents.each do |descendent|
      #    logger.info "Descendent is #{descendent}"
    end
    x =y
  end

  def tidy_up
    logger.info "tidy up params: #{params.inspect}"
    SearchQuery.tidy_up(params[:tidy_user_id])
    respond_to do |format|
      format.js
    end
  end

  def process_more_results
    logger.info "process_more_results: #{params.inspect}"
    process_output = SearchQuery.process_more_results(params[:more_results_query_id])
    @unprocessed_sentence_count = process_output[:unprocessed_sentence_count]
    @found_results = process_output[:found_results]
    @first_index = [1, params[:more_results_first_result_id].to_i - process_output[:absolute_first]+1].max
    @last_index = [params[:more_results_last_result_id].to_i, process_output[:absolute_last]].min - process_output[:absolute_first]+1
#    logger.info "process_more_results @first_index= #{ @first_index }, @last_index = #{@last_index}, @unprocessed_sentence_count = #{@unprocessed_sentence_count}, "
# logger.info "params[:more_results_last_result_id] = #{params[:more_results_last_result_id]}, process_output[:absolute_first] = #{process_output[:absolute_first]}, process_output[:absolute_last] = #{process_output[:absolute_last]}"

    respond_to do |format|
      format.js
    end
  end

  def previous_search
    logger.info "previous_search: #{params.inspect}"
    current_index = 0
    more_resultsa(params[:prev_query_id], current_index, MAX_DISPLAY)
    respond_to do |format|
      format.js
    end
  end

  def more_resultsa(query_id, current_index, range)
    fetch_output = SearchQuery.fetch(query_id, current_index, range)
    @search_results = fetch_output[:fetch_results]
    @query_id = query_id
    if @search_results.length > 0
      @first_result_id = @search_results[0].id
      @last_result_id = @search_results[-1].id
      @absolute_last = fetch_output[:absolute_last]
      @absolute_first =fetch_output[:absolute_first]
      @found_results = fetch_output[:found_results]
      #    logger.info "more_result - first item: #{@search_results[0].inspect}"

      if @first_result_id > fetch_output[:absolute_first]
        @show_previous = true
      else
        @show_previous = false
      end
      @unprocessed_sentence_count = fetch_output[:unprocessed_sentence_count]
      if @last_result_id < fetch_output[:absolute_last] or @unprocessed_sentence_count > 0
        @show_next = true
      else
        @show_next =false
      end
    else
      @first_result_id =0
      @last_result_id = 0
      @absolute_last = 0
      @absolute_first = 0
      @found_results = 0
      @show_next =false
      @show_previous = false
    end

  end

  def more_results
    more_resultsa(params[:results_query_id].to_i, params[:results_current_index].to_i, params[:results_range].to_i)

    respond_to do |format|
      format.js
    end
  end

  def search
    logger.info "DomainCrawlersController search called"
#    logger.info "check #{params[:row_in_list]}"
    search_query = SearchQuery.new();
    search_query.create(params, current_user);
    @query_id = search_query.id
#  crawler_debug
    if params[:search_type] == "search_domains"
      @search_groups1 = false
    else
      @search_groups1 = true
    end


    @domain_length = 0;
    @search_results = [];
    @unprocessed_sentence_count = 0
    @first_result_id = 0
    @last_result_id = 0
    @show_previous = false
    @show_next = false


    search_output = search_query.search();

    if search_output[:search_results].length >0
      @search_results = search_output[:search_results]
      @first_result_id = @search_results[0].id
      @last_result_id = @search_results[-1].id
      @show_previous = false
      if search_output[:unprocessed_sentence_count] >0
        @show_next = true
      else
        @show_next = false
      end
      @unprocessed_sentence_count = search_output[:unprocessed_sentence_count]
      #   logger.info "Search @first_result_id = #{ @first_result_id }, @last_result_id = #{@last_result_id}, @unprocessed_sentence_count = #{@unprocessed_sentence_count} "


    end
    @truncate_length = search_output[:truncate_length]
    @domain_length = 1
    crawler_range = CrawlerRange.where('user_id = ? and begin_id = ? and end_id = ?', current_user.id, CrawlerPage.first.id + 1, CrawlerPage.last.id).first
    if crawler_range
      @domain_length = 0
    end


    respond_to do |format|
      format.js
    end

  end


  def create
    logger.info "DomainCrawlersController create called"
    @result_str = ""
    # logger.info "DomainCrawlersController params inspect #{domain_crawler_params.inspect}"
    @domain_crawler = DomainCrawler.new(domain_crawler_params)
    #  logger.info "DomainCrawlersController @domain_crawler inspect #{@domain_crawler.inspect}"
    if @domain_crawler.save
      case params[:new_domain_action]
        when "new_domain"


          #   logger.info "DomainCrawlersController create, after new"

          #    logger.info "DomainCrawlersController create, after save, inspect #{@domain_crawler.inspect}"
          first_page_id = @domain_crawler.crawl(params[:flow_str])


        when "grab_domain"
          first_page_id = @domain_crawler.grab_domain(params[:filter])
      end
      if first_page_id !=0
        #    logger.info "Crawl success first_id = #{first_page_id}"
        @domain_crawler.crawler_page_id = CrawlerPage.find_by_id(first_page_id).root.id
        @domain_crawler.save



        #   logger.info "DomainCrawlersController create, before redirect"
        redirect_to domain_crawlers_url, notice: "Domain Analysis of #{@domain_crawler.domain_home_page} was successfull!"
      else
        #   logger.info "crawl failure"
        @domain_crawler.destroy
        #   logger.info "DomainCrawlersController create, before redirect"
        redirect_to domain_crawlers_url, notice: "Domain Analysis failed of  #{@domain_crawler.domain_home_page} failed. Is the domain address correct?"
      end
    end

  end

  def delete_result
    logger.info "delete_result begin"
    @delete_id = params[:id]
    SearchResult.destroy(@delete_id)
    respond_to do |format|
      format.js
    end
  end



  def remove_group_result

    logger.info "remove_group_result begin"
    @group_search_result_list = params[:group_search_result_list].map(&:to_i)
    @group_search_result_list.each do |group_search_result|
      GroupElement.destroy(group_search_result)
    end
    user_paragraph_str = "SELECT * FROM user_paragraphs up WHERE up.user_id = #{current_user.id} AND\
 (SELECT COUNT(*) FROM group_elements ge WHERE ge.user_id = #{current_user.id} AND ge.paragraph_id = up.paragraph_id) = 0"
    delete_str = "DELETE FROM user_paragraphs up WHERE up.user_id = #{current_user.id} AND\
 (SELECT COUNT(*) FROM group_elements ge WHERE ge.user_id = #{current_user.id} AND ge.paragraph_id = up.paragraph_id) = 0"
    ActiveRecord::Base.connection.execute(delete_str)

    respond_to do |format|
      format.js
    end
  end

  def display_group
    logger.info "display_group begin"
    @group_id = params[:id]
    respond_to do |format|
      format.js
    end
  end

  def create_group(params)
    new_group = GroupName.new
    new_group.name = params[:group_action_name]
    new_group.parent_id = params[:group_radio]
    new_group.user_id = current_user.id
    new_group.save
    @group_selected = GROUP_ACTION[:new_group]
    @group_parent_id = new_group.parent_id
    @result_str = ""
  end


  def rename_group(params)
    group_name = GroupName.find_by_id(params[:group_radio]);
    group_name.name = params[:group_action_name];
    group_name.save
    @group_selected = GROUP_ACTION[:rename]
    @group_parent_id = group_name.parent_id
    @result_str = ""
  end

  def move_group(params)
    group_name = GroupName.find_by_id(params[:group_radio]);
    new_parent = GroupName.find_by_id(params[:move_location_group_radio]);
    ancestor_ids = new_parent.ancestor_ids
#    logger.info "move_group ancestors: #{ancestor_ids}, group_name_id = #{group_name.id}"
    if ancestor_ids.index(group_name.id) != nil

      @result_str = "You cannot move a parent to one of its children"
    else
      group_name.parent_id = new_parent.id
      group_name.save;
      @result_str = ""
    end
#   logger.info "move_group result_str = #{@result_str}"

    @group_selected = GROUP_ACTION[:move_group]
    @group_parent_id = group_name.parent_id

  end

  def remove_group(params)
    @group_selected = GROUP_ACTION[:remove_group]
    group_name = GroupName.find_by_id(params[:remove_group])
    if group_name != nil
      @group_parent_id = group_name.parent_id

app/helpers/domain_crawlers_helper.rb
module DomainCrawlersHelper
end

app/views/domain_crawlers/_groups.html.erb
<div class="result-groups" id="result-groups">
  <div class="float-left">
    <h3>Groups</h3></div>
  <%= render 'domain_crawlers/showhide', div_name: "result-groups" %>


  <div class="float-clear" name="result-groups">
    <div>
      <select id="select-group-action" name="select-group-action" onChange="SelectGroupAction()">
        <option <% if args[:selected] == GROUP_ACTION[:select_action] %> selected <% end %> value= <%= GROUP_ACTION[:select_action] %> > Select Group Action</option>
        <option <% if args[:selected] == GROUP_ACTION[:new_group]%> selected <% end %>  value= <%= GROUP_ACTION[:new_group]%> > New Group</option>
        <option <% if args[:selected] == GROUP_ACTION[:rename] %> selected <% end %>  value= <%= GROUP_ACTION[:rename]%> > Rename Group</option>
        <option <% if args[:selected] == GROUP_ACTION[:move_group]%> selected <% end %>  value= <%= GROUP_ACTION[:move_group]%> > Move Group</option>
        <option <% if args[:selected] == GROUP_ACTION[:remove_group] %> selected <% end %>  value= <%= GROUP_ACTION[:remove_group]%> > Remove Group</option>
        <option <% if args[:selected] == GROUP_ACTION[:add_element] %> selected <% end %>  value= <%= GROUP_ACTION[:add_element]%> > Add Search Results</option>
        <option <% if args[:selected] == GROUP_ACTION[:remove_element] %> selected <% end %>  value= <%= GROUP_ACTION[:remove_element]%> > Remove Results From Group</option>


      </select>
    </div>

    <div>
      <%= form_tag group_action_path, :id => 'group_action_form', method: 'get', remote: true do %>
          <div class="group-names">
            <ul id="group_names_list" name="ul-group-name-#{root_group.id}">
              <li>

                <%= render 'domain_crawlers/group_expand_buttons', id: root_group.id %>
                <%= render 'domain_crawlers/group_name', args: {:group_name => root_group.name, :group_name_id => root_group.id, :root => true} %>
              </li>
              <%= render 'domain_crawlers/user_groups', args: {:group_names => root_group.root.descendants.arrange, :parent_id => root_group.id} %>
            </ul>
          </div>
          <div> <%= hidden_field_tag :remove_group, params[:remove_group] %></div>
          <div class="group-field group_action_name">
            <label for="group_action_name" id = "group_action_name">Group action name</label>:<br/>
            <%= text_field_tag :group_action_name, params[:group_action_name] %>
          </div>
          <div class="actions group-field group-action-button" ><%= submit_tag "New Group", id: "group-action-button" %></div>
      <% end %>
    </div>
    <div><input type="button" class="group-field" name="remove_elements_button"  value="Remove From Group" onclick= RemoveFromGroup() ></div>
    <div id="group_notice"></div>
  </div>
</div>

<script>SelectGroupAction();</script>
<script>SelectDomainAction();</script>

app/views/domain_crawlers/_new_domain_form.html.erb
<div class="domain-new domain-field">
  <div class="float-left">
    <h3>New Domain</h3>
  </div>

  <div class="float-clear" name="domain-new">
    <%= form_for args[:domain_crawler] do |f| %>
        <% if args[:domain_crawler].errors.any? %>
            <div class="error_messages">
              <h2>Form is invalid</h2>
              <ul>
                <% args[:domain_crawler].errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>



        <div class="field">
          <%= f.label :domain_home_page %><br/>
          <%= f.text_field :domain_home_page %>
        </div>
        <div class="field">
          <%= f.label :short_name %><br/>
          <%= f.text_field :short_name %>
        </div>
        <div class="field">
          <%= f.label :description %><br/>
          <%= f.text_field :description %>
        </div>
        <div class="field">
          <%= label_tag :filter %><br/>
          <%= text_field_tag :filter %>
        </div>

        <div class="field">
          <%= label_tag :new_domain_action %><br/>
          <%= text_field_tag :new_domain_action %>
        </div>


        <div class="field">
          <%= f.hidden_field :user_id, :value => args[:user_id] %>
        </div>

        <div class="actions"><%= f.submit "Crawl Domain" %></div>
    <% end %>
  </div>
</div>

app/views/domain_crawlers/_show_prev_next.html.erb
<div  id = "show-prev-next">
<% if args[:show_previous] %>
    <span  class = "prev-link" onclick="MoreResults(<%=args[:first_result_id]%>,<%=-MAX_DISPLAY%>)">
    (Previous <%= MAX_DISPLAY %>)
  </span>
<% end %>
<% if args[:show_next]  %>
    <span  class = "next-link"  onclick="MoreResults(<%=args[:last_result_id]%>,<%=MAX_DISPLAY%>)">
    (Next  <%= MAX_DISPLAY %>)
  </span>
<% end %>
</div>

app/views/domain_crawlers/_showhide.html.erb
<div class="show-link" name="show_link_<%=div_name%>" onclick="ShowItem('<%=div_name%>');">show</div>
<div class="hide-link" name="hide_link_<%=div_name%>" onclick="HideItem('<%=div_name%>');">hide</div>

app/views/domain_crawlers/_submenu_crawler_pages.erb
<% crawler_page = args[:crawler_page] %>


    <%= render 'domain_crawlers/url', args: {:crawler_page => crawler_page, :crawler_page_ranges => args[:crawler_page_ranges]} %>
    <%= render 'domain_crawlers/children_crawler_pages', args: {:crawler_page => crawler_page, :crawler_page_ranges => args[:crawler_page_ranges]} %>


app/views/domain_crawlers/_url.html.erb
<% crawler_page = args[:crawler_page] %>
<% crawler_page_ranges = args[:crawler_page_ranges] %>
<% if crawler_page.result_page_id == nil or crawler_page.result_page_id < 0 %>

    <li class="bad_page" name= "li-crawler-page-<%=crawler_page.id%>"> This page is bad
      <% good_page = false  %>
<% else %>
    <li class="good_page" name= "li-crawler-page-<%=crawler_page.id%>">
      <% good_page = true %>
<% end %>

<% if crawler_page.has_good_children? %>
    <% display_node = DisplayNode.exists?(user_id: current_user.id, crawler_page_id: crawler_page.id) %>
<%= render 'domain_crawlers/expand_buttons', args: {:id => crawler_page.id, :display_node => display_node} %>
    <%end%>

<div class="domain-url">
  <% if crawler_page.root? == false %>
<%= link_to crawler_page.name, crawler_page.URL, target: '_blank'%>
      <% else %>
      <% domain_crawler =crawler_page.domain_crawler %>
      <% if domain_crawler %>
      <%= link_to domain_crawler.short_name, crawler_page.URL, target: '_blank'%>
          <% end %>
  <% end %>
</div>
<% if good_page == true %>
<div class="domain-field domain-checkbox"> <input type="checkbox" id="checkbox-domain-selector-<%= crawler_page.id %>"  class="check" <% if crawler_page.in_range?(crawler_page_ranges)%> checked <% end %> value=<%= crawler_page.id  %> onclick="CrawlerPageRange(<%=crawler_page.id %>);"></div>
<% end %>
<div class="domain-name-radio domain-field" >
  <input type="radio" name ="domain_radio" <% if crawler_page.root? %> checked <% end %> value=<%=crawler_page.id %> id="domain-name-<%=crawler_page.id %>"  >
</div>
<div class="move-location-domain-name-radio domain-field" >
  <input type="radio" name ="move_location_domain_radio" <% if crawler_page.root? %> checked <% end %> value=<%=crawler_page.id %> id="move-location-domain-name-<%=crawler_page.id %>"  >
</div>
<div class="remove-domain domain-field" onclick="RemoveDomain(<%= crawler_page.id %>)">
  Remove
</div>
</li>

app/views/domain_crawlers/_user_groups.html.erb
<ul class="child-group-name" name="ul-group-name-<%=args[:parent_id]%>" style="display: none" >

  <% args[:group_names].each do |group_name, children| %>

      <li>
        <% if children.present? %>
            <%= render 'domain_crawlers/group_expand_buttons', id: group_name.id %>
            <%= render 'domain_crawlers/group_name', args:{:group_name => group_name.name, :group_name_id => group_name.id, :root => false} %>
            <%= render 'domain_crawlers/user_groups', args: {:group_names => children, :parent_id => group_name.id}  %>
        <% else %>
            <%= render 'domain_crawlers/group_name', args:{:group_name => group_name.name, :group_name_id => group_name.id, :root => false} %>
        <% end %>
      </li>
  <% end %>
</ul>

app/views/domain_crawlers/add_result.js.erb
$("#group_notice").empty();
$("#group_notice").show();
$("#group_notice").text("<%= @result_str %>");

app/views/domain_crawlers/expand_contract_action.js.erb
$('[name="li-crawler-page-<%=@expand_contract_crawler_page.id%>"]').replaceWith('<%= j render "domain_crawlers/url", args: {:crawler_page => @expand_contract_crawler_page, :crawler_page_ranges => @crawler_page_ranges} %>');
$('[name="ul-crawler-page-<%=@expand_contract_crawler_page.id%>"]').replaceWith('<%= j render "domain_crawlers/children_crawler_pages", args: {:crawler_page => @expand_contract_crawler_page, :crawler_page_ranges => @crawler_page_ranges} %>');
SelectDomainAction()

app/views/domain_crawlers/index.js.erb
SelectDomain(@crawler_page_id);
//$('[name="domain_summary_header"]').replaceWith(<%= render 'domain_crawlers/domain_summary_header' %>);

app/views/domain_crawlers/new_group.js.erb
$('#result-groups').replaceWith('<%= j render "domain_crawlers/groups" %>');
<% group_id = @group_parent_id %>
<% while group_id != nil %>
expandGroupName(<%= group_id %>);
<% group_id = GroupName.find_by_id(group_id).parent_id%>
<% end %>

var $radios = $('input:radio[name=group_radio]');
$radios.filter('[value=<%= @group_parent_id %>]').prop('checked', true);

$("#group_notice").empty();

app/views/domain_crawlers/previous_search.js.erb
ShowSearchResults();

$('#search-results').replaceWith('<%= j render "search_results/display_results", args: {:user_id => current_user.id, :first_result_id => @first_result_id, :last_result_id => @last_result_id, :show_previous => @show_previous, :show_next => @show_next, :query_id => @query_id}%>');
$('#show-prev-next').replaceWith('<%= j render "domain_crawlers/show_prev_next", args: {:first_result_id => @first_result_id, :last_result_id => @last_result_id, :show_previous => @show_previous, :show_next => @show_next}%>');

$("#group_notice").empty();
$("#search_notice").empty();
$("#search_notice").show();
<% if @search_results.length >0 %>
$("#search_notice").text("Showing  <%= @first_result_id - @absolute_first +1 %> to <%= @last_result_id - @absolute_first +1  %> of <%= @found_results %>, Unprocessed Results: <%= @unprocessed_sentence_count %>");


<% end %>

app/views/domain_crawlers/process_more_results.js.erb
$("#search_notice").text("Showing <%= @first_index  %> to <%= @last_index %> of <%= @found_results %>, Unprocessed Results: <%= @unprocessed_sentence_count %>");

<% if @unprocessed_sentence_count >0 %>
ProcessMore()
<% else %>
TidyUp()
<% end %>

app/views/domain_crawlers/remove_group_result.js.erb
<% @group_search_result_list.each do |group_search_result| %>
$("[name='group-search-result-<%=group_search_result%>']").remove();
<% end %>