config/routes.rb
Rails.application.routes.draw do
  resources :domain_crawlers
  resources :search_queries
  resources :group_names
  resources :search_results
  resources :regex_templates
  get 'password_resets/new'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'

  get 'logout', to: 'sessions#destroy', as: 'logout'

  get "/set_header" => 'domain_crawlers#set_header', as: 'set_header'

  get "/display_group" => 'domain_crawlers#display_group', as: 'display_group'

  get "/delete_result" => 'domain_crawlers#delete_result', as: 'delete_result'

  post 'search', to: 'domain_crawlers#search', as: 'search'

  get 'group_action', to: 'domain_crawlers#group_action', as: 'group_action'
  get 'expand_contract_action', to: 'domain_crawlers#expand_contract_action', as: 'expand_contract_action'
  get 'apple-touch-icon-120x120-precomposed.png', to: redirect('/assets/favicon/apple-touch-icon-120x120-precomposed.png')
  get 'apple-touch-icon-120x120.png', to: redirect('/assets/favicon/apple-touch-icon-120x120.png')
  get 'apple-touch-icon.png', to: redirect('/assets/favicon/apple-touch-icon.png')
  get 'apple-touch-icon-precomposed.png', to: redirect('/assets/favicon/apple-touch-icon-precomposed.png')
  get 'apple-touch-icon-152x152.png', to: redirect('/assets/favicon/apple-touch-icon-152x152.png')
  get 'apple-touch-icon-152x152-precomposed.png', to: redirect('/assets/favicon/apple-touch-icon-152x152-precomposed.png')


  get 'domain_action', to: 'domain_crawlers#domain_action', as: 'domain_action'
  get 'more_results', to: 'domain_crawlers#more_results', as: 'more_results'
  get 'process_more_results', to: 'domain_crawlers#process_more_results', as: 'process_more_results'
  get 'previous_search', to: 'domain_crawlers#previous_search', as: 'previous_search'
  get 'tidy_up', to: 'domain_crawlers#tidy_up', as: 'tidy_up'
  post 'add_result', to:'domain_crawlers#add_result', as: 'add_result'
  post 'remove_group_result', to:'domain_crawlers#remove_group_result', as: 'remove_group_result'


  resources :users
  resources :sessions
  resources :password_resets


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'users#index'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password(validations: false)
  has_many :domain_crawlers

  validates_uniqueness_of :email, unless: :guest?
  validates_presence_of :password, :on => :create, unless: :guest?

  before_create { generate_token(:auth_token) }
  def self.new_guest
    logger.info "*** calling self.new_guest"
    new_guest_user = User.new
    new_guest_user.guest = true
    new_guest_user.save!


    return new_guest_user

  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    logger.info "UsersController new called"
    @user = User.new
  end





  def create
    logger.info "UsersController create called"
    index
    logger.info "User params inspect #{user_params.inspect}"

    @user = User.new(user_params)
    if @user.save and verify_recaptcha(model: @user)
      cookies[:auth_token] = @user.auth_token
      logger.info "catpcha verified"

      redirect_to new_domain_crawler_path
    else
      logger.info "catpcha unverified"
      render "new"
    end
  end

  def index
    logger.info "UsersController index called"
    @users = User.all
  end

  def update
    if @user.update_attributes(params[:user])
      sign_in @user
      flash[:success] = "Profile updated"
      redirect_to new_domain_crawler_path
    else
      render 'edit'
    end
  end

  private

  def user_params
    logger.info "UsersController user_params called"
    params.require(:user).permit(:email, :first_name, :second_name, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_header.html.erb
<div class="user-header">
  <div class="dominican-logo"></div>
  <div class="thomas-header"> St. Thomas <br> The Search Engine </div>
  <div class="login-status-div">
  <% if !current_user.guest %>
      Logged in as <%= current_user.email %>. <br>
      <%= link_to "Log Out", logout_path %>
  <% else %>
      <%= link_to "Sign Up", signup_path %> or
      <%= link_to "Log In", login_path %>
  <% end %>
  </div>
</div>

app/views/users/new.html.erb


<h1>Sign Up</h1>

<%= form_for @user do |f| %>
    <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :first_name%><br />
      <%= f.text_field :first_name %>
    </div>
    <div class="field">
      <%= f.label :second_name%><br />
      <%= f.text_field :second_name %>
    </div>
    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </div>

    <%= recaptcha_tags %>


    <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>

<script>HideForms();</script>